x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/workspace
  working_dir: /workspace

services:
  workspace:
    <<: *common
    command: /bin/bash
    stdin_open: true
    tty: true

  build-all:
    <<: *common
    command: ./build_all.sh

  build-all-clean:
    <<: *common
    command: ./build_all.sh clean
